# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DlgSqlWindow.ui'
#
# Created: Fri Jul  1 00:59:20 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DlgSqlWindow(object):
    def setupUi(self, DlgSqlWindow):
        DlgSqlWindow.setObjectName(_fromUtf8("DlgSqlWindow"))
        DlgSqlWindow.resize(738, 494)
        self.gridLayout_2 = QtGui.QGridLayout(DlgSqlWindow)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(DlgSqlWindow)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.editSql = QtGui.QTextEdit(DlgSqlWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.editSql.sizePolicy().hasHeightForWidth())
        self.editSql.setSizePolicy(sizePolicy)
        self.editSql.setObjectName(_fromUtf8("editSql"))
        self.gridLayout_2.addWidget(self.editSql, 1, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.btnExecute = QtGui.QPushButton(DlgSqlWindow)
        self.btnExecute.setObjectName(_fromUtf8("btnExecute"))
        self.hboxlayout.addWidget(self.btnExecute)
        self.lblResult = QtGui.QLabel(DlgSqlWindow)
        self.lblResult.setText(_fromUtf8(""))
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.hboxlayout.addWidget(self.lblResult)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnClear = QtGui.QPushButton(DlgSqlWindow)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.hboxlayout.addWidget(self.btnClear)
        self.gridLayout_2.addLayout(self.hboxlayout, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(DlgSqlWindow)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.viewResult = QtGui.QTableView(DlgSqlWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.viewResult.sizePolicy().hasHeightForWidth())
        self.viewResult.setSizePolicy(sizePolicy)
        self.viewResult.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.viewResult.setObjectName(_fromUtf8("viewResult"))
        self.gridLayout_2.addWidget(self.viewResult, 4, 0, 1, 1)
        self.loadAsLayerGroup = QtGui.QGroupBox(DlgSqlWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadAsLayerGroup.sizePolicy().hasHeightForWidth())
        self.loadAsLayerGroup.setSizePolicy(sizePolicy)
        self.loadAsLayerGroup.setCheckable(True)
        self.loadAsLayerGroup.setChecked(True)
        self.loadAsLayerGroup.setObjectName(_fromUtf8("loadAsLayerGroup"))
        self.gridLayout = QtGui.QGridLayout(self.loadAsLayerGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.loadAsLayerWidget = QtGui.QWidget(self.loadAsLayerGroup)
        self.loadAsLayerWidget.setObjectName(_fromUtf8("loadAsLayerWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.loadAsLayerWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.loadAsLayerWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.geomCombo = QtGui.QComboBox(self.loadAsLayerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomCombo.sizePolicy().hasHeightForWidth())
        self.geomCombo.setSizePolicy(sizePolicy)
        self.geomCombo.setEditable(True)
        self.geomCombo.setObjectName(_fromUtf8("geomCombo"))
        self.horizontalLayout_6.addWidget(self.geomCombo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.loadAsLayerWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.uniqueCombo = QtGui.QComboBox(self.loadAsLayerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uniqueCombo.sizePolicy().hasHeightForWidth())
        self.uniqueCombo.setSizePolicy(sizePolicy)
        self.uniqueCombo.setEditable(True)
        self.uniqueCombo.setObjectName(_fromUtf8("uniqueCombo"))
        self.horizontalLayout_6.addWidget(self.uniqueCombo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.getColumnsBtn = QtGui.QPushButton(self.loadAsLayerWidget)
        self.getColumnsBtn.setObjectName(_fromUtf8("getColumnsBtn"))
        self.horizontalLayout_6.addWidget(self.getColumnsBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.loadAsLayerWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.layerNameEdit = QtGui.QLineEdit(self.loadAsLayerWidget)
        self.layerNameEdit.setEnabled(True)
        self.layerNameEdit.setText(_fromUtf8(""))
        self.layerNameEdit.setObjectName(_fromUtf8("layerNameEdit"))
        self.horizontalLayout_7.addWidget(self.layerNameEdit)
        self.pushButton = QtGui.QPushButton(self.loadAsLayerWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.loadAsLayerWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.loadAsLayerGroup, 5, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DlgSqlWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 6, 0, 1, 1)
        self.label_3.setBuddy(self.geomCombo)
        self.label_4.setBuddy(self.uniqueCombo)

        self.retranslateUi(DlgSqlWindow)
        QtCore.QMetaObject.connectSlotsByName(DlgSqlWindow)
        DlgSqlWindow.setTabOrder(self.editSql, self.btnExecute)
        DlgSqlWindow.setTabOrder(self.btnExecute, self.btnClear)
        DlgSqlWindow.setTabOrder(self.btnClear, self.viewResult)

    def retranslateUi(self, DlgSqlWindow):
        DlgSqlWindow.setWindowTitle(QtGui.QApplication.translate("DlgSqlWindow", "SQL window", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgSqlWindow", "SQL query:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExecute.setText(QtGui.QApplication.translate("DlgSqlWindow", "&Execute (F5)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExecute.setShortcut(QtGui.QApplication.translate("DlgSqlWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setText(QtGui.QApplication.translate("DlgSqlWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgSqlWindow", "Result:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadAsLayerGroup.setTitle(QtGui.QApplication.translate("DlgSqlWindow", "Load as new layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DlgSqlWindow", "Geometry column", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DlgSqlWindow", "Column with unique \n"
"integer values", None, QtGui.QApplication.UnicodeUTF8))
        self.getColumnsBtn.setText(QtGui.QApplication.translate("DlgSqlWindow", "Retrieve \n"
"columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DlgSqlWindow", "New layer name (prefix)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DlgSqlWindow", "Load now!", None, QtGui.QApplication.UnicodeUTF8))

